version: '3.8'
services:
  web:
    container_name: movie-search
    build:
      context: ./
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - ./.env
    volumes:
      - ./app/:/app
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local